apiVersion: v1
kind: Service
metadata:
  name: goapp
  labels:
    app: goapp
spec:
  selector:
    app: goapp
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer